# Generated by Django 3.1.4 on 2020-12-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
